server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  data:
    mongodb:
      uri: mongodb://root:mima@112.126.101.188:27017/test

#  db.createUser(
#  {
#    user:"root",
#    pwd:"mima",
#    roles:[{role:"root", db:"admin"}]
#  }
#  )