server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#  datasource:
#    primary:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://112.126.101.188:3306/testdb1?serverTimezone=UTC&useSSL=false
#      username: root
#      password: mima
#    secondary:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://112.126.101.188:3306/testdb2?serverTimezone=UTC&useSSL=false
#      username: root
#      password: mima

primarydb:
  uniqueResourceName: primary
  xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
  xaProperties:
    url: jdbc:mysql://112.126.101.188:3306/testdb1?serverTimezone=UTC&useSSL=false
    user: root
    password: mima
  exclusiveConnectionMode: true
  minPoolSize: 3
  maxPoolSize: 10
  testQuery: SELECT 1 from dual #由于采用HikiriCP，用于检测数据库连接是否存活。

secondarydb:
  uniqueResourceName: secondary
#  xaDataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
  xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
  xaProperties:
    url: jdbc:mysql://112.126.101.188:3306/testdb2?serverTimezone=UTC&useSSL=false
    user: root
    password: mima
  exclusiveConnectionMode: true
  minPoolSize: 3
  maxPoolSize: 10
  testQuery: SELECT 1 from dual #由于采用HikiriCP，用于检测数据库连接是否存活。