server:
  port: 8080
main:
  allow-bean-definition-overriding: true
spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    primary:
      url: jdbc:mysql://112.126.101.188:3306/testdb1?serverTimezone=UTC&useSSL=false
      username: root
      password: mima
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://112.126.101.188:3306/testdb2?serverTimezone=UTC&useSSL=false
      username: root
      password: mima
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
      connectionfactory:
        max-pool-size: 20
        borrow-connection-timeout: 60











family:
  family-name: "happy \n family"
  father:
    name: zimug
    age: 17
  mother:
    alias:
      - lovly
      - alice
  child:
    name: kobo
    age: ${family.father.age:5b }
    friends:
      - hobby: football
        sex: male
      - hobby: basketball
        sex: female

